
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const RequestCategory = {
  ILUMINACAO: 'ILUMINACAO',
  PAVIMENTACAO: 'PAVIMENTACAO',
  COLETA_LIXO: 'COLETA_LIXO',
  LIMPEZA: 'LIMPEZA',
  SINALIZACAO: 'SINALIZACAO',
  TRANSPORTE: 'TRANSPORTE',
  OUTROS: 'OUTROS'
} as const

export type RequestCategory = (typeof RequestCategory)[keyof typeof RequestCategory]


export const RequestStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED'
} as const

export type RequestStatus = (typeof RequestStatus)[keyof typeof RequestStatus]


export const Priority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
} as const

export type Priority = (typeof Priority)[keyof typeof Priority]
