
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RequestResponse` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RequestResponse
 * 
 */
export type RequestResponseModel = runtime.Types.Result.DefaultSelection<Prisma.$RequestResponsePayload>

export type AggregateRequestResponse = {
  _count: RequestResponseCountAggregateOutputType | null
  _min: RequestResponseMinAggregateOutputType | null
  _max: RequestResponseMaxAggregateOutputType | null
}

export type RequestResponseMinAggregateOutputType = {
  id: string | null
  requestId: string | null
  userId: string | null
  message: string | null
  createdAt: Date | null
}

export type RequestResponseMaxAggregateOutputType = {
  id: string | null
  requestId: string | null
  userId: string | null
  message: string | null
  createdAt: Date | null
}

export type RequestResponseCountAggregateOutputType = {
  id: number
  requestId: number
  userId: number
  message: number
  createdAt: number
  _all: number
}


export type RequestResponseMinAggregateInputType = {
  id?: true
  requestId?: true
  userId?: true
  message?: true
  createdAt?: true
}

export type RequestResponseMaxAggregateInputType = {
  id?: true
  requestId?: true
  userId?: true
  message?: true
  createdAt?: true
}

export type RequestResponseCountAggregateInputType = {
  id?: true
  requestId?: true
  userId?: true
  message?: true
  createdAt?: true
  _all?: true
}

export type RequestResponseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RequestResponse to aggregate.
   */
  where?: Prisma.RequestResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestResponses to fetch.
   */
  orderBy?: Prisma.RequestResponseOrderByWithRelationInput | Prisma.RequestResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RequestResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RequestResponses
  **/
  _count?: true | RequestResponseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RequestResponseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RequestResponseMaxAggregateInputType
}

export type GetRequestResponseAggregateType<T extends RequestResponseAggregateArgs> = {
      [P in keyof T & keyof AggregateRequestResponse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRequestResponse[P]>
    : Prisma.GetScalarType<T[P], AggregateRequestResponse[P]>
}




export type RequestResponseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestResponseWhereInput
  orderBy?: Prisma.RequestResponseOrderByWithAggregationInput | Prisma.RequestResponseOrderByWithAggregationInput[]
  by: Prisma.RequestResponseScalarFieldEnum[] | Prisma.RequestResponseScalarFieldEnum
  having?: Prisma.RequestResponseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RequestResponseCountAggregateInputType | true
  _min?: RequestResponseMinAggregateInputType
  _max?: RequestResponseMaxAggregateInputType
}

export type RequestResponseGroupByOutputType = {
  id: string
  requestId: string
  userId: string
  message: string
  createdAt: Date
  _count: RequestResponseCountAggregateOutputType | null
  _min: RequestResponseMinAggregateOutputType | null
  _max: RequestResponseMaxAggregateOutputType | null
}

type GetRequestResponseGroupByPayload<T extends RequestResponseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RequestResponseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RequestResponseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RequestResponseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RequestResponseGroupByOutputType[P]>
      }
    >
  >



export type RequestResponseWhereInput = {
  AND?: Prisma.RequestResponseWhereInput | Prisma.RequestResponseWhereInput[]
  OR?: Prisma.RequestResponseWhereInput[]
  NOT?: Prisma.RequestResponseWhereInput | Prisma.RequestResponseWhereInput[]
  id?: Prisma.StringFilter<"RequestResponse"> | string
  requestId?: Prisma.StringFilter<"RequestResponse"> | string
  userId?: Prisma.StringFilter<"RequestResponse"> | string
  message?: Prisma.StringFilter<"RequestResponse"> | string
  createdAt?: Prisma.DateTimeFilter<"RequestResponse"> | Date | string
  request?: Prisma.XOR<Prisma.ServiceRequestScalarRelationFilter, Prisma.ServiceRequestWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type RequestResponseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  request?: Prisma.ServiceRequestOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.RequestResponseOrderByRelevanceInput
}

export type RequestResponseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RequestResponseWhereInput | Prisma.RequestResponseWhereInput[]
  OR?: Prisma.RequestResponseWhereInput[]
  NOT?: Prisma.RequestResponseWhereInput | Prisma.RequestResponseWhereInput[]
  requestId?: Prisma.StringFilter<"RequestResponse"> | string
  userId?: Prisma.StringFilter<"RequestResponse"> | string
  message?: Prisma.StringFilter<"RequestResponse"> | string
  createdAt?: Prisma.DateTimeFilter<"RequestResponse"> | Date | string
  request?: Prisma.XOR<Prisma.ServiceRequestScalarRelationFilter, Prisma.ServiceRequestWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type RequestResponseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.RequestResponseCountOrderByAggregateInput
  _max?: Prisma.RequestResponseMaxOrderByAggregateInput
  _min?: Prisma.RequestResponseMinOrderByAggregateInput
}

export type RequestResponseScalarWhereWithAggregatesInput = {
  AND?: Prisma.RequestResponseScalarWhereWithAggregatesInput | Prisma.RequestResponseScalarWhereWithAggregatesInput[]
  OR?: Prisma.RequestResponseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RequestResponseScalarWhereWithAggregatesInput | Prisma.RequestResponseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RequestResponse"> | string
  requestId?: Prisma.StringWithAggregatesFilter<"RequestResponse"> | string
  userId?: Prisma.StringWithAggregatesFilter<"RequestResponse"> | string
  message?: Prisma.StringWithAggregatesFilter<"RequestResponse"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RequestResponse"> | Date | string
}

export type RequestResponseCreateInput = {
  id?: string
  message: string
  createdAt?: Date | string
  request: Prisma.ServiceRequestCreateNestedOneWithoutResponsesInput
  user: Prisma.UserCreateNestedOneWithoutResponsesInput
}

export type RequestResponseUncheckedCreateInput = {
  id?: string
  requestId: string
  userId: string
  message: string
  createdAt?: Date | string
}

export type RequestResponseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  request?: Prisma.ServiceRequestUpdateOneRequiredWithoutResponsesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutResponsesNestedInput
}

export type RequestResponseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestResponseCreateManyInput = {
  id?: string
  requestId: string
  userId: string
  message: string
  createdAt?: Date | string
}

export type RequestResponseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestResponseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestResponseListRelationFilter = {
  every?: Prisma.RequestResponseWhereInput
  some?: Prisma.RequestResponseWhereInput
  none?: Prisma.RequestResponseWhereInput
}

export type RequestResponseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RequestResponseOrderByRelevanceInput = {
  fields: Prisma.RequestResponseOrderByRelevanceFieldEnum | Prisma.RequestResponseOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type RequestResponseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RequestResponseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RequestResponseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RequestResponseCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.RequestResponseCreateWithoutUserInput, Prisma.RequestResponseUncheckedCreateWithoutUserInput> | Prisma.RequestResponseCreateWithoutUserInput[] | Prisma.RequestResponseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RequestResponseCreateOrConnectWithoutUserInput | Prisma.RequestResponseCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.RequestResponseCreateManyUserInputEnvelope
  connect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
}

export type RequestResponseUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.RequestResponseCreateWithoutUserInput, Prisma.RequestResponseUncheckedCreateWithoutUserInput> | Prisma.RequestResponseCreateWithoutUserInput[] | Prisma.RequestResponseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RequestResponseCreateOrConnectWithoutUserInput | Prisma.RequestResponseCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.RequestResponseCreateManyUserInputEnvelope
  connect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
}

export type RequestResponseUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.RequestResponseCreateWithoutUserInput, Prisma.RequestResponseUncheckedCreateWithoutUserInput> | Prisma.RequestResponseCreateWithoutUserInput[] | Prisma.RequestResponseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RequestResponseCreateOrConnectWithoutUserInput | Prisma.RequestResponseCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.RequestResponseUpsertWithWhereUniqueWithoutUserInput | Prisma.RequestResponseUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.RequestResponseCreateManyUserInputEnvelope
  set?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  disconnect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  delete?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  connect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  update?: Prisma.RequestResponseUpdateWithWhereUniqueWithoutUserInput | Prisma.RequestResponseUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.RequestResponseUpdateManyWithWhereWithoutUserInput | Prisma.RequestResponseUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.RequestResponseScalarWhereInput | Prisma.RequestResponseScalarWhereInput[]
}

export type RequestResponseUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.RequestResponseCreateWithoutUserInput, Prisma.RequestResponseUncheckedCreateWithoutUserInput> | Prisma.RequestResponseCreateWithoutUserInput[] | Prisma.RequestResponseUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.RequestResponseCreateOrConnectWithoutUserInput | Prisma.RequestResponseCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.RequestResponseUpsertWithWhereUniqueWithoutUserInput | Prisma.RequestResponseUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.RequestResponseCreateManyUserInputEnvelope
  set?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  disconnect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  delete?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  connect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  update?: Prisma.RequestResponseUpdateWithWhereUniqueWithoutUserInput | Prisma.RequestResponseUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.RequestResponseUpdateManyWithWhereWithoutUserInput | Prisma.RequestResponseUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.RequestResponseScalarWhereInput | Prisma.RequestResponseScalarWhereInput[]
}

export type RequestResponseCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.RequestResponseCreateWithoutRequestInput, Prisma.RequestResponseUncheckedCreateWithoutRequestInput> | Prisma.RequestResponseCreateWithoutRequestInput[] | Prisma.RequestResponseUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestResponseCreateOrConnectWithoutRequestInput | Prisma.RequestResponseCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.RequestResponseCreateManyRequestInputEnvelope
  connect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
}

export type RequestResponseUncheckedCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.RequestResponseCreateWithoutRequestInput, Prisma.RequestResponseUncheckedCreateWithoutRequestInput> | Prisma.RequestResponseCreateWithoutRequestInput[] | Prisma.RequestResponseUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestResponseCreateOrConnectWithoutRequestInput | Prisma.RequestResponseCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.RequestResponseCreateManyRequestInputEnvelope
  connect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
}

export type RequestResponseUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.RequestResponseCreateWithoutRequestInput, Prisma.RequestResponseUncheckedCreateWithoutRequestInput> | Prisma.RequestResponseCreateWithoutRequestInput[] | Prisma.RequestResponseUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestResponseCreateOrConnectWithoutRequestInput | Prisma.RequestResponseCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.RequestResponseUpsertWithWhereUniqueWithoutRequestInput | Prisma.RequestResponseUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.RequestResponseCreateManyRequestInputEnvelope
  set?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  disconnect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  delete?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  connect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  update?: Prisma.RequestResponseUpdateWithWhereUniqueWithoutRequestInput | Prisma.RequestResponseUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.RequestResponseUpdateManyWithWhereWithoutRequestInput | Prisma.RequestResponseUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.RequestResponseScalarWhereInput | Prisma.RequestResponseScalarWhereInput[]
}

export type RequestResponseUncheckedUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.RequestResponseCreateWithoutRequestInput, Prisma.RequestResponseUncheckedCreateWithoutRequestInput> | Prisma.RequestResponseCreateWithoutRequestInput[] | Prisma.RequestResponseUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestResponseCreateOrConnectWithoutRequestInput | Prisma.RequestResponseCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.RequestResponseUpsertWithWhereUniqueWithoutRequestInput | Prisma.RequestResponseUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.RequestResponseCreateManyRequestInputEnvelope
  set?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  disconnect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  delete?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  connect?: Prisma.RequestResponseWhereUniqueInput | Prisma.RequestResponseWhereUniqueInput[]
  update?: Prisma.RequestResponseUpdateWithWhereUniqueWithoutRequestInput | Prisma.RequestResponseUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.RequestResponseUpdateManyWithWhereWithoutRequestInput | Prisma.RequestResponseUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.RequestResponseScalarWhereInput | Prisma.RequestResponseScalarWhereInput[]
}

export type RequestResponseCreateWithoutUserInput = {
  id?: string
  message: string
  createdAt?: Date | string
  request: Prisma.ServiceRequestCreateNestedOneWithoutResponsesInput
}

export type RequestResponseUncheckedCreateWithoutUserInput = {
  id?: string
  requestId: string
  message: string
  createdAt?: Date | string
}

export type RequestResponseCreateOrConnectWithoutUserInput = {
  where: Prisma.RequestResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.RequestResponseCreateWithoutUserInput, Prisma.RequestResponseUncheckedCreateWithoutUserInput>
}

export type RequestResponseCreateManyUserInputEnvelope = {
  data: Prisma.RequestResponseCreateManyUserInput | Prisma.RequestResponseCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type RequestResponseUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.RequestResponseWhereUniqueInput
  update: Prisma.XOR<Prisma.RequestResponseUpdateWithoutUserInput, Prisma.RequestResponseUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.RequestResponseCreateWithoutUserInput, Prisma.RequestResponseUncheckedCreateWithoutUserInput>
}

export type RequestResponseUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.RequestResponseWhereUniqueInput
  data: Prisma.XOR<Prisma.RequestResponseUpdateWithoutUserInput, Prisma.RequestResponseUncheckedUpdateWithoutUserInput>
}

export type RequestResponseUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.RequestResponseScalarWhereInput
  data: Prisma.XOR<Prisma.RequestResponseUpdateManyMutationInput, Prisma.RequestResponseUncheckedUpdateManyWithoutUserInput>
}

export type RequestResponseScalarWhereInput = {
  AND?: Prisma.RequestResponseScalarWhereInput | Prisma.RequestResponseScalarWhereInput[]
  OR?: Prisma.RequestResponseScalarWhereInput[]
  NOT?: Prisma.RequestResponseScalarWhereInput | Prisma.RequestResponseScalarWhereInput[]
  id?: Prisma.StringFilter<"RequestResponse"> | string
  requestId?: Prisma.StringFilter<"RequestResponse"> | string
  userId?: Prisma.StringFilter<"RequestResponse"> | string
  message?: Prisma.StringFilter<"RequestResponse"> | string
  createdAt?: Prisma.DateTimeFilter<"RequestResponse"> | Date | string
}

export type RequestResponseCreateWithoutRequestInput = {
  id?: string
  message: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutResponsesInput
}

export type RequestResponseUncheckedCreateWithoutRequestInput = {
  id?: string
  userId: string
  message: string
  createdAt?: Date | string
}

export type RequestResponseCreateOrConnectWithoutRequestInput = {
  where: Prisma.RequestResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.RequestResponseCreateWithoutRequestInput, Prisma.RequestResponseUncheckedCreateWithoutRequestInput>
}

export type RequestResponseCreateManyRequestInputEnvelope = {
  data: Prisma.RequestResponseCreateManyRequestInput | Prisma.RequestResponseCreateManyRequestInput[]
  skipDuplicates?: boolean
}

export type RequestResponseUpsertWithWhereUniqueWithoutRequestInput = {
  where: Prisma.RequestResponseWhereUniqueInput
  update: Prisma.XOR<Prisma.RequestResponseUpdateWithoutRequestInput, Prisma.RequestResponseUncheckedUpdateWithoutRequestInput>
  create: Prisma.XOR<Prisma.RequestResponseCreateWithoutRequestInput, Prisma.RequestResponseUncheckedCreateWithoutRequestInput>
}

export type RequestResponseUpdateWithWhereUniqueWithoutRequestInput = {
  where: Prisma.RequestResponseWhereUniqueInput
  data: Prisma.XOR<Prisma.RequestResponseUpdateWithoutRequestInput, Prisma.RequestResponseUncheckedUpdateWithoutRequestInput>
}

export type RequestResponseUpdateManyWithWhereWithoutRequestInput = {
  where: Prisma.RequestResponseScalarWhereInput
  data: Prisma.XOR<Prisma.RequestResponseUpdateManyMutationInput, Prisma.RequestResponseUncheckedUpdateManyWithoutRequestInput>
}

export type RequestResponseCreateManyUserInput = {
  id?: string
  requestId: string
  message: string
  createdAt?: Date | string
}

export type RequestResponseUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  request?: Prisma.ServiceRequestUpdateOneRequiredWithoutResponsesNestedInput
}

export type RequestResponseUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestResponseUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestResponseCreateManyRequestInput = {
  id?: string
  userId: string
  message: string
  createdAt?: Date | string
}

export type RequestResponseUpdateWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutResponsesNestedInput
}

export type RequestResponseUncheckedUpdateWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestResponseUncheckedUpdateManyWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RequestResponseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  userId?: boolean
  message?: boolean
  createdAt?: boolean
  request?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestResponse"]>

export type RequestResponseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  userId?: boolean
  message?: boolean
  createdAt?: boolean
  request?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestResponse"]>

export type RequestResponseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  userId?: boolean
  message?: boolean
  createdAt?: boolean
  request?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestResponse"]>

export type RequestResponseSelectScalar = {
  id?: boolean
  requestId?: boolean
  userId?: boolean
  message?: boolean
  createdAt?: boolean
}

export type RequestResponseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "requestId" | "userId" | "message" | "createdAt", ExtArgs["result"]["requestResponse"]>
export type RequestResponseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type RequestResponseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type RequestResponseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.ServiceRequestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $RequestResponsePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RequestResponse"
  objects: {
    request: Prisma.$ServiceRequestPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    requestId: string
    userId: string
    message: string
    createdAt: Date
  }, ExtArgs["result"]["requestResponse"]>
  composites: {}
}

export type RequestResponseGetPayload<S extends boolean | null | undefined | RequestResponseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload, S>

export type RequestResponseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RequestResponseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RequestResponseCountAggregateInputType | true
  }

export interface RequestResponseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RequestResponse'], meta: { name: 'RequestResponse' } }
  /**
   * Find zero or one RequestResponse that matches the filter.
   * @param {RequestResponseFindUniqueArgs} args - Arguments to find a RequestResponse
   * @example
   * // Get one RequestResponse
   * const requestResponse = await prisma.requestResponse.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RequestResponseFindUniqueArgs>(args: Prisma.SelectSubset<T, RequestResponseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RequestResponseClient<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RequestResponse that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RequestResponseFindUniqueOrThrowArgs} args - Arguments to find a RequestResponse
   * @example
   * // Get one RequestResponse
   * const requestResponse = await prisma.requestResponse.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RequestResponseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RequestResponseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RequestResponseClient<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RequestResponse that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestResponseFindFirstArgs} args - Arguments to find a RequestResponse
   * @example
   * // Get one RequestResponse
   * const requestResponse = await prisma.requestResponse.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RequestResponseFindFirstArgs>(args?: Prisma.SelectSubset<T, RequestResponseFindFirstArgs<ExtArgs>>): Prisma.Prisma__RequestResponseClient<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RequestResponse that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestResponseFindFirstOrThrowArgs} args - Arguments to find a RequestResponse
   * @example
   * // Get one RequestResponse
   * const requestResponse = await prisma.requestResponse.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RequestResponseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RequestResponseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RequestResponseClient<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RequestResponses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestResponseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RequestResponses
   * const requestResponses = await prisma.requestResponse.findMany()
   * 
   * // Get first 10 RequestResponses
   * const requestResponses = await prisma.requestResponse.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const requestResponseWithIdOnly = await prisma.requestResponse.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RequestResponseFindManyArgs>(args?: Prisma.SelectSubset<T, RequestResponseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RequestResponse.
   * @param {RequestResponseCreateArgs} args - Arguments to create a RequestResponse.
   * @example
   * // Create one RequestResponse
   * const RequestResponse = await prisma.requestResponse.create({
   *   data: {
   *     // ... data to create a RequestResponse
   *   }
   * })
   * 
   */
  create<T extends RequestResponseCreateArgs>(args: Prisma.SelectSubset<T, RequestResponseCreateArgs<ExtArgs>>): Prisma.Prisma__RequestResponseClient<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RequestResponses.
   * @param {RequestResponseCreateManyArgs} args - Arguments to create many RequestResponses.
   * @example
   * // Create many RequestResponses
   * const requestResponse = await prisma.requestResponse.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RequestResponseCreateManyArgs>(args?: Prisma.SelectSubset<T, RequestResponseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RequestResponses and returns the data saved in the database.
   * @param {RequestResponseCreateManyAndReturnArgs} args - Arguments to create many RequestResponses.
   * @example
   * // Create many RequestResponses
   * const requestResponse = await prisma.requestResponse.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RequestResponses and only return the `id`
   * const requestResponseWithIdOnly = await prisma.requestResponse.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RequestResponseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RequestResponseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RequestResponse.
   * @param {RequestResponseDeleteArgs} args - Arguments to delete one RequestResponse.
   * @example
   * // Delete one RequestResponse
   * const RequestResponse = await prisma.requestResponse.delete({
   *   where: {
   *     // ... filter to delete one RequestResponse
   *   }
   * })
   * 
   */
  delete<T extends RequestResponseDeleteArgs>(args: Prisma.SelectSubset<T, RequestResponseDeleteArgs<ExtArgs>>): Prisma.Prisma__RequestResponseClient<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RequestResponse.
   * @param {RequestResponseUpdateArgs} args - Arguments to update one RequestResponse.
   * @example
   * // Update one RequestResponse
   * const requestResponse = await prisma.requestResponse.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RequestResponseUpdateArgs>(args: Prisma.SelectSubset<T, RequestResponseUpdateArgs<ExtArgs>>): Prisma.Prisma__RequestResponseClient<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RequestResponses.
   * @param {RequestResponseDeleteManyArgs} args - Arguments to filter RequestResponses to delete.
   * @example
   * // Delete a few RequestResponses
   * const { count } = await prisma.requestResponse.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RequestResponseDeleteManyArgs>(args?: Prisma.SelectSubset<T, RequestResponseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RequestResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestResponseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RequestResponses
   * const requestResponse = await prisma.requestResponse.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RequestResponseUpdateManyArgs>(args: Prisma.SelectSubset<T, RequestResponseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RequestResponses and returns the data updated in the database.
   * @param {RequestResponseUpdateManyAndReturnArgs} args - Arguments to update many RequestResponses.
   * @example
   * // Update many RequestResponses
   * const requestResponse = await prisma.requestResponse.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RequestResponses and only return the `id`
   * const requestResponseWithIdOnly = await prisma.requestResponse.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RequestResponseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RequestResponseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RequestResponse.
   * @param {RequestResponseUpsertArgs} args - Arguments to update or create a RequestResponse.
   * @example
   * // Update or create a RequestResponse
   * const requestResponse = await prisma.requestResponse.upsert({
   *   create: {
   *     // ... data to create a RequestResponse
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RequestResponse we want to update
   *   }
   * })
   */
  upsert<T extends RequestResponseUpsertArgs>(args: Prisma.SelectSubset<T, RequestResponseUpsertArgs<ExtArgs>>): Prisma.Prisma__RequestResponseClient<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RequestResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestResponseCountArgs} args - Arguments to filter RequestResponses to count.
   * @example
   * // Count the number of RequestResponses
   * const count = await prisma.requestResponse.count({
   *   where: {
   *     // ... the filter for the RequestResponses we want to count
   *   }
   * })
  **/
  count<T extends RequestResponseCountArgs>(
    args?: Prisma.Subset<T, RequestResponseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RequestResponseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RequestResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestResponseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RequestResponseAggregateArgs>(args: Prisma.Subset<T, RequestResponseAggregateArgs>): Prisma.PrismaPromise<GetRequestResponseAggregateType<T>>

  /**
   * Group by RequestResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestResponseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RequestResponseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RequestResponseGroupByArgs['orderBy'] }
      : { orderBy?: RequestResponseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RequestResponseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRequestResponseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RequestResponse model
 */
readonly fields: RequestResponseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RequestResponse.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RequestResponseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  request<T extends Prisma.ServiceRequestDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceRequestDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RequestResponse model
 */
export interface RequestResponseFieldRefs {
  readonly id: Prisma.FieldRef<"RequestResponse", 'String'>
  readonly requestId: Prisma.FieldRef<"RequestResponse", 'String'>
  readonly userId: Prisma.FieldRef<"RequestResponse", 'String'>
  readonly message: Prisma.FieldRef<"RequestResponse", 'String'>
  readonly createdAt: Prisma.FieldRef<"RequestResponse", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RequestResponse findUnique
 */
export type RequestResponseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  /**
   * Filter, which RequestResponse to fetch.
   */
  where: Prisma.RequestResponseWhereUniqueInput
}

/**
 * RequestResponse findUniqueOrThrow
 */
export type RequestResponseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  /**
   * Filter, which RequestResponse to fetch.
   */
  where: Prisma.RequestResponseWhereUniqueInput
}

/**
 * RequestResponse findFirst
 */
export type RequestResponseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  /**
   * Filter, which RequestResponse to fetch.
   */
  where?: Prisma.RequestResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestResponses to fetch.
   */
  orderBy?: Prisma.RequestResponseOrderByWithRelationInput | Prisma.RequestResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RequestResponses.
   */
  cursor?: Prisma.RequestResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestResponses.
   */
  distinct?: Prisma.RequestResponseScalarFieldEnum | Prisma.RequestResponseScalarFieldEnum[]
}

/**
 * RequestResponse findFirstOrThrow
 */
export type RequestResponseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  /**
   * Filter, which RequestResponse to fetch.
   */
  where?: Prisma.RequestResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestResponses to fetch.
   */
  orderBy?: Prisma.RequestResponseOrderByWithRelationInput | Prisma.RequestResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RequestResponses.
   */
  cursor?: Prisma.RequestResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestResponses.
   */
  distinct?: Prisma.RequestResponseScalarFieldEnum | Prisma.RequestResponseScalarFieldEnum[]
}

/**
 * RequestResponse findMany
 */
export type RequestResponseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  /**
   * Filter, which RequestResponses to fetch.
   */
  where?: Prisma.RequestResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestResponses to fetch.
   */
  orderBy?: Prisma.RequestResponseOrderByWithRelationInput | Prisma.RequestResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RequestResponses.
   */
  cursor?: Prisma.RequestResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestResponses.
   */
  skip?: number
  distinct?: Prisma.RequestResponseScalarFieldEnum | Prisma.RequestResponseScalarFieldEnum[]
}

/**
 * RequestResponse create
 */
export type RequestResponseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  /**
   * The data needed to create a RequestResponse.
   */
  data: Prisma.XOR<Prisma.RequestResponseCreateInput, Prisma.RequestResponseUncheckedCreateInput>
}

/**
 * RequestResponse createMany
 */
export type RequestResponseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RequestResponses.
   */
  data: Prisma.RequestResponseCreateManyInput | Prisma.RequestResponseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RequestResponse createManyAndReturn
 */
export type RequestResponseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * The data used to create many RequestResponses.
   */
  data: Prisma.RequestResponseCreateManyInput | Prisma.RequestResponseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RequestResponse update
 */
export type RequestResponseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  /**
   * The data needed to update a RequestResponse.
   */
  data: Prisma.XOR<Prisma.RequestResponseUpdateInput, Prisma.RequestResponseUncheckedUpdateInput>
  /**
   * Choose, which RequestResponse to update.
   */
  where: Prisma.RequestResponseWhereUniqueInput
}

/**
 * RequestResponse updateMany
 */
export type RequestResponseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RequestResponses.
   */
  data: Prisma.XOR<Prisma.RequestResponseUpdateManyMutationInput, Prisma.RequestResponseUncheckedUpdateManyInput>
  /**
   * Filter which RequestResponses to update
   */
  where?: Prisma.RequestResponseWhereInput
  /**
   * Limit how many RequestResponses to update.
   */
  limit?: number
}

/**
 * RequestResponse updateManyAndReturn
 */
export type RequestResponseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * The data used to update RequestResponses.
   */
  data: Prisma.XOR<Prisma.RequestResponseUpdateManyMutationInput, Prisma.RequestResponseUncheckedUpdateManyInput>
  /**
   * Filter which RequestResponses to update
   */
  where?: Prisma.RequestResponseWhereInput
  /**
   * Limit how many RequestResponses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RequestResponse upsert
 */
export type RequestResponseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  /**
   * The filter to search for the RequestResponse to update in case it exists.
   */
  where: Prisma.RequestResponseWhereUniqueInput
  /**
   * In case the RequestResponse found by the `where` argument doesn't exist, create a new RequestResponse with this data.
   */
  create: Prisma.XOR<Prisma.RequestResponseCreateInput, Prisma.RequestResponseUncheckedCreateInput>
  /**
   * In case the RequestResponse was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RequestResponseUpdateInput, Prisma.RequestResponseUncheckedUpdateInput>
}

/**
 * RequestResponse delete
 */
export type RequestResponseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  /**
   * Filter which RequestResponse to delete.
   */
  where: Prisma.RequestResponseWhereUniqueInput
}

/**
 * RequestResponse deleteMany
 */
export type RequestResponseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RequestResponses to delete
   */
  where?: Prisma.RequestResponseWhereInput
  /**
   * Limit how many RequestResponses to delete.
   */
  limit?: number
}

/**
 * RequestResponse without action
 */
export type RequestResponseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
}
