
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ServiceRequest
 * 
 */
export type ServiceRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceRequestPayload>

export type AggregateServiceRequest = {
  _count: ServiceRequestCountAggregateOutputType | null
  _min: ServiceRequestMinAggregateOutputType | null
  _max: ServiceRequestMaxAggregateOutputType | null
}

export type ServiceRequestMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  category: $Enums.RequestCategory | null
  status: $Enums.RequestStatus | null
  priority: $Enums.Priority | null
  location: string | null
  userId: string | null
  assignedTo: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ServiceRequestMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  category: $Enums.RequestCategory | null
  status: $Enums.RequestStatus | null
  priority: $Enums.Priority | null
  location: string | null
  userId: string | null
  assignedTo: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ServiceRequestCountAggregateOutputType = {
  id: number
  title: number
  description: number
  category: number
  status: number
  priority: number
  location: number
  userId: number
  assignedTo: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ServiceRequestMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  category?: true
  status?: true
  priority?: true
  location?: true
  userId?: true
  assignedTo?: true
  createdAt?: true
  updatedAt?: true
}

export type ServiceRequestMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  category?: true
  status?: true
  priority?: true
  location?: true
  userId?: true
  assignedTo?: true
  createdAt?: true
  updatedAt?: true
}

export type ServiceRequestCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  category?: true
  status?: true
  priority?: true
  location?: true
  userId?: true
  assignedTo?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ServiceRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceRequest to aggregate.
   */
  where?: Prisma.ServiceRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceRequests to fetch.
   */
  orderBy?: Prisma.ServiceRequestOrderByWithRelationInput | Prisma.ServiceRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceRequests
  **/
  _count?: true | ServiceRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceRequestMaxAggregateInputType
}

export type GetServiceRequestAggregateType<T extends ServiceRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceRequest[P]>
}




export type ServiceRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceRequestWhereInput
  orderBy?: Prisma.ServiceRequestOrderByWithAggregationInput | Prisma.ServiceRequestOrderByWithAggregationInput[]
  by: Prisma.ServiceRequestScalarFieldEnum[] | Prisma.ServiceRequestScalarFieldEnum
  having?: Prisma.ServiceRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceRequestCountAggregateInputType | true
  _min?: ServiceRequestMinAggregateInputType
  _max?: ServiceRequestMaxAggregateInputType
}

export type ServiceRequestGroupByOutputType = {
  id: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status: $Enums.RequestStatus
  priority: $Enums.Priority
  location: string | null
  userId: string
  assignedTo: string | null
  createdAt: Date
  updatedAt: Date
  _count: ServiceRequestCountAggregateOutputType | null
  _min: ServiceRequestMinAggregateOutputType | null
  _max: ServiceRequestMaxAggregateOutputType | null
}

type GetServiceRequestGroupByPayload<T extends ServiceRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceRequestGroupByOutputType[P]>
      }
    >
  >



export type ServiceRequestWhereInput = {
  AND?: Prisma.ServiceRequestWhereInput | Prisma.ServiceRequestWhereInput[]
  OR?: Prisma.ServiceRequestWhereInput[]
  NOT?: Prisma.ServiceRequestWhereInput | Prisma.ServiceRequestWhereInput[]
  id?: Prisma.StringFilter<"ServiceRequest"> | string
  title?: Prisma.StringFilter<"ServiceRequest"> | string
  description?: Prisma.StringFilter<"ServiceRequest"> | string
  category?: Prisma.EnumRequestCategoryFilter<"ServiceRequest"> | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFilter<"ServiceRequest"> | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFilter<"ServiceRequest"> | $Enums.Priority
  location?: Prisma.StringNullableFilter<"ServiceRequest"> | string | null
  userId?: Prisma.StringFilter<"ServiceRequest"> | string
  assignedTo?: Prisma.StringNullableFilter<"ServiceRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ServiceRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceRequest"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  responses?: Prisma.RequestResponseListRelationFilter
  notifications?: Prisma.NotificationListRelationFilter
}

export type ServiceRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  responses?: Prisma.RequestResponseOrderByRelationAggregateInput
  notifications?: Prisma.NotificationOrderByRelationAggregateInput
  _relevance?: Prisma.ServiceRequestOrderByRelevanceInput
}

export type ServiceRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ServiceRequestWhereInput | Prisma.ServiceRequestWhereInput[]
  OR?: Prisma.ServiceRequestWhereInput[]
  NOT?: Prisma.ServiceRequestWhereInput | Prisma.ServiceRequestWhereInput[]
  title?: Prisma.StringFilter<"ServiceRequest"> | string
  description?: Prisma.StringFilter<"ServiceRequest"> | string
  category?: Prisma.EnumRequestCategoryFilter<"ServiceRequest"> | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFilter<"ServiceRequest"> | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFilter<"ServiceRequest"> | $Enums.Priority
  location?: Prisma.StringNullableFilter<"ServiceRequest"> | string | null
  userId?: Prisma.StringFilter<"ServiceRequest"> | string
  assignedTo?: Prisma.StringNullableFilter<"ServiceRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ServiceRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceRequest"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  responses?: Prisma.RequestResponseListRelationFilter
  notifications?: Prisma.NotificationListRelationFilter
}, "id">

export type ServiceRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ServiceRequestCountOrderByAggregateInput
  _max?: Prisma.ServiceRequestMaxOrderByAggregateInput
  _min?: Prisma.ServiceRequestMinOrderByAggregateInput
}

export type ServiceRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceRequestScalarWhereWithAggregatesInput | Prisma.ServiceRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceRequestScalarWhereWithAggregatesInput | Prisma.ServiceRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ServiceRequest"> | string
  title?: Prisma.StringWithAggregatesFilter<"ServiceRequest"> | string
  description?: Prisma.StringWithAggregatesFilter<"ServiceRequest"> | string
  category?: Prisma.EnumRequestCategoryWithAggregatesFilter<"ServiceRequest"> | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusWithAggregatesFilter<"ServiceRequest"> | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityWithAggregatesFilter<"ServiceRequest"> | $Enums.Priority
  location?: Prisma.StringNullableWithAggregatesFilter<"ServiceRequest"> | string | null
  userId?: Prisma.StringWithAggregatesFilter<"ServiceRequest"> | string
  assignedTo?: Prisma.StringNullableWithAggregatesFilter<"ServiceRequest"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceRequest"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceRequest"> | Date | string
}

export type ServiceRequestCreateInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRequestsInput
  responses?: Prisma.RequestResponseCreateNestedManyWithoutRequestInput
  notifications?: Prisma.NotificationCreateNestedManyWithoutRequestInput
}

export type ServiceRequestUncheckedCreateInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  userId: string
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.RequestResponseUncheckedCreateNestedManyWithoutRequestInput
  notifications?: Prisma.NotificationUncheckedCreateNestedManyWithoutRequestInput
}

export type ServiceRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRequestsNestedInput
  responses?: Prisma.RequestResponseUpdateManyWithoutRequestNestedInput
  notifications?: Prisma.NotificationUpdateManyWithoutRequestNestedInput
}

export type ServiceRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.RequestResponseUncheckedUpdateManyWithoutRequestNestedInput
  notifications?: Prisma.NotificationUncheckedUpdateManyWithoutRequestNestedInput
}

export type ServiceRequestCreateManyInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  userId: string
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceRequestListRelationFilter = {
  every?: Prisma.ServiceRequestWhereInput
  some?: Prisma.ServiceRequestWhereInput
  none?: Prisma.ServiceRequestWhereInput
}

export type ServiceRequestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ServiceRequestOrderByRelevanceInput = {
  fields: Prisma.ServiceRequestOrderByRelevanceFieldEnum | Prisma.ServiceRequestOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ServiceRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  location?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ServiceRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  location?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ServiceRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  location?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedTo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ServiceRequestScalarRelationFilter = {
  is?: Prisma.ServiceRequestWhereInput
  isNot?: Prisma.ServiceRequestWhereInput
}

export type ServiceRequestCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ServiceRequestCreateWithoutUserInput, Prisma.ServiceRequestUncheckedCreateWithoutUserInput> | Prisma.ServiceRequestCreateWithoutUserInput[] | Prisma.ServiceRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ServiceRequestCreateOrConnectWithoutUserInput | Prisma.ServiceRequestCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ServiceRequestCreateManyUserInputEnvelope
  connect?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
}

export type ServiceRequestUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ServiceRequestCreateWithoutUserInput, Prisma.ServiceRequestUncheckedCreateWithoutUserInput> | Prisma.ServiceRequestCreateWithoutUserInput[] | Prisma.ServiceRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ServiceRequestCreateOrConnectWithoutUserInput | Prisma.ServiceRequestCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ServiceRequestCreateManyUserInputEnvelope
  connect?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
}

export type ServiceRequestUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceRequestCreateWithoutUserInput, Prisma.ServiceRequestUncheckedCreateWithoutUserInput> | Prisma.ServiceRequestCreateWithoutUserInput[] | Prisma.ServiceRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ServiceRequestCreateOrConnectWithoutUserInput | Prisma.ServiceRequestCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ServiceRequestUpsertWithWhereUniqueWithoutUserInput | Prisma.ServiceRequestUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ServiceRequestCreateManyUserInputEnvelope
  set?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
  disconnect?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
  delete?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
  connect?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
  update?: Prisma.ServiceRequestUpdateWithWhereUniqueWithoutUserInput | Prisma.ServiceRequestUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ServiceRequestUpdateManyWithWhereWithoutUserInput | Prisma.ServiceRequestUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ServiceRequestScalarWhereInput | Prisma.ServiceRequestScalarWhereInput[]
}

export type ServiceRequestUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceRequestCreateWithoutUserInput, Prisma.ServiceRequestUncheckedCreateWithoutUserInput> | Prisma.ServiceRequestCreateWithoutUserInput[] | Prisma.ServiceRequestUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ServiceRequestCreateOrConnectWithoutUserInput | Prisma.ServiceRequestCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ServiceRequestUpsertWithWhereUniqueWithoutUserInput | Prisma.ServiceRequestUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ServiceRequestCreateManyUserInputEnvelope
  set?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
  disconnect?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
  delete?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
  connect?: Prisma.ServiceRequestWhereUniqueInput | Prisma.ServiceRequestWhereUniqueInput[]
  update?: Prisma.ServiceRequestUpdateWithWhereUniqueWithoutUserInput | Prisma.ServiceRequestUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ServiceRequestUpdateManyWithWhereWithoutUserInput | Prisma.ServiceRequestUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ServiceRequestScalarWhereInput | Prisma.ServiceRequestScalarWhereInput[]
}

export type EnumRequestCategoryFieldUpdateOperationsInput = {
  set?: $Enums.RequestCategory
}

export type EnumRequestStatusFieldUpdateOperationsInput = {
  set?: $Enums.RequestStatus
}

export type EnumPriorityFieldUpdateOperationsInput = {
  set?: $Enums.Priority
}

export type ServiceRequestCreateNestedOneWithoutResponsesInput = {
  create?: Prisma.XOR<Prisma.ServiceRequestCreateWithoutResponsesInput, Prisma.ServiceRequestUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.ServiceRequestCreateOrConnectWithoutResponsesInput
  connect?: Prisma.ServiceRequestWhereUniqueInput
}

export type ServiceRequestUpdateOneRequiredWithoutResponsesNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceRequestCreateWithoutResponsesInput, Prisma.ServiceRequestUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.ServiceRequestCreateOrConnectWithoutResponsesInput
  upsert?: Prisma.ServiceRequestUpsertWithoutResponsesInput
  connect?: Prisma.ServiceRequestWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceRequestUpdateToOneWithWhereWithoutResponsesInput, Prisma.ServiceRequestUpdateWithoutResponsesInput>, Prisma.ServiceRequestUncheckedUpdateWithoutResponsesInput>
}

export type ServiceRequestCreateNestedOneWithoutNotificationsInput = {
  create?: Prisma.XOR<Prisma.ServiceRequestCreateWithoutNotificationsInput, Prisma.ServiceRequestUncheckedCreateWithoutNotificationsInput>
  connectOrCreate?: Prisma.ServiceRequestCreateOrConnectWithoutNotificationsInput
  connect?: Prisma.ServiceRequestWhereUniqueInput
}

export type ServiceRequestUpdateOneRequiredWithoutNotificationsNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceRequestCreateWithoutNotificationsInput, Prisma.ServiceRequestUncheckedCreateWithoutNotificationsInput>
  connectOrCreate?: Prisma.ServiceRequestCreateOrConnectWithoutNotificationsInput
  upsert?: Prisma.ServiceRequestUpsertWithoutNotificationsInput
  connect?: Prisma.ServiceRequestWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceRequestUpdateToOneWithWhereWithoutNotificationsInput, Prisma.ServiceRequestUpdateWithoutNotificationsInput>, Prisma.ServiceRequestUncheckedUpdateWithoutNotificationsInput>
}

export type ServiceRequestCreateWithoutUserInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.RequestResponseCreateNestedManyWithoutRequestInput
  notifications?: Prisma.NotificationCreateNestedManyWithoutRequestInput
}

export type ServiceRequestUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.RequestResponseUncheckedCreateNestedManyWithoutRequestInput
  notifications?: Prisma.NotificationUncheckedCreateNestedManyWithoutRequestInput
}

export type ServiceRequestCreateOrConnectWithoutUserInput = {
  where: Prisma.ServiceRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceRequestCreateWithoutUserInput, Prisma.ServiceRequestUncheckedCreateWithoutUserInput>
}

export type ServiceRequestCreateManyUserInputEnvelope = {
  data: Prisma.ServiceRequestCreateManyUserInput | Prisma.ServiceRequestCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ServiceRequestUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ServiceRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceRequestUpdateWithoutUserInput, Prisma.ServiceRequestUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ServiceRequestCreateWithoutUserInput, Prisma.ServiceRequestUncheckedCreateWithoutUserInput>
}

export type ServiceRequestUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ServiceRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceRequestUpdateWithoutUserInput, Prisma.ServiceRequestUncheckedUpdateWithoutUserInput>
}

export type ServiceRequestUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ServiceRequestScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceRequestUpdateManyMutationInput, Prisma.ServiceRequestUncheckedUpdateManyWithoutUserInput>
}

export type ServiceRequestScalarWhereInput = {
  AND?: Prisma.ServiceRequestScalarWhereInput | Prisma.ServiceRequestScalarWhereInput[]
  OR?: Prisma.ServiceRequestScalarWhereInput[]
  NOT?: Prisma.ServiceRequestScalarWhereInput | Prisma.ServiceRequestScalarWhereInput[]
  id?: Prisma.StringFilter<"ServiceRequest"> | string
  title?: Prisma.StringFilter<"ServiceRequest"> | string
  description?: Prisma.StringFilter<"ServiceRequest"> | string
  category?: Prisma.EnumRequestCategoryFilter<"ServiceRequest"> | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFilter<"ServiceRequest"> | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFilter<"ServiceRequest"> | $Enums.Priority
  location?: Prisma.StringNullableFilter<"ServiceRequest"> | string | null
  userId?: Prisma.StringFilter<"ServiceRequest"> | string
  assignedTo?: Prisma.StringNullableFilter<"ServiceRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ServiceRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceRequest"> | Date | string
}

export type ServiceRequestCreateWithoutResponsesInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRequestsInput
  notifications?: Prisma.NotificationCreateNestedManyWithoutRequestInput
}

export type ServiceRequestUncheckedCreateWithoutResponsesInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  userId: string
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  notifications?: Prisma.NotificationUncheckedCreateNestedManyWithoutRequestInput
}

export type ServiceRequestCreateOrConnectWithoutResponsesInput = {
  where: Prisma.ServiceRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceRequestCreateWithoutResponsesInput, Prisma.ServiceRequestUncheckedCreateWithoutResponsesInput>
}

export type ServiceRequestUpsertWithoutResponsesInput = {
  update: Prisma.XOR<Prisma.ServiceRequestUpdateWithoutResponsesInput, Prisma.ServiceRequestUncheckedUpdateWithoutResponsesInput>
  create: Prisma.XOR<Prisma.ServiceRequestCreateWithoutResponsesInput, Prisma.ServiceRequestUncheckedCreateWithoutResponsesInput>
  where?: Prisma.ServiceRequestWhereInput
}

export type ServiceRequestUpdateToOneWithWhereWithoutResponsesInput = {
  where?: Prisma.ServiceRequestWhereInput
  data: Prisma.XOR<Prisma.ServiceRequestUpdateWithoutResponsesInput, Prisma.ServiceRequestUncheckedUpdateWithoutResponsesInput>
}

export type ServiceRequestUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRequestsNestedInput
  notifications?: Prisma.NotificationUpdateManyWithoutRequestNestedInput
}

export type ServiceRequestUncheckedUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notifications?: Prisma.NotificationUncheckedUpdateManyWithoutRequestNestedInput
}

export type ServiceRequestCreateWithoutNotificationsInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRequestsInput
  responses?: Prisma.RequestResponseCreateNestedManyWithoutRequestInput
}

export type ServiceRequestUncheckedCreateWithoutNotificationsInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  userId: string
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.RequestResponseUncheckedCreateNestedManyWithoutRequestInput
}

export type ServiceRequestCreateOrConnectWithoutNotificationsInput = {
  where: Prisma.ServiceRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceRequestCreateWithoutNotificationsInput, Prisma.ServiceRequestUncheckedCreateWithoutNotificationsInput>
}

export type ServiceRequestUpsertWithoutNotificationsInput = {
  update: Prisma.XOR<Prisma.ServiceRequestUpdateWithoutNotificationsInput, Prisma.ServiceRequestUncheckedUpdateWithoutNotificationsInput>
  create: Prisma.XOR<Prisma.ServiceRequestCreateWithoutNotificationsInput, Prisma.ServiceRequestUncheckedCreateWithoutNotificationsInput>
  where?: Prisma.ServiceRequestWhereInput
}

export type ServiceRequestUpdateToOneWithWhereWithoutNotificationsInput = {
  where?: Prisma.ServiceRequestWhereInput
  data: Prisma.XOR<Prisma.ServiceRequestUpdateWithoutNotificationsInput, Prisma.ServiceRequestUncheckedUpdateWithoutNotificationsInput>
}

export type ServiceRequestUpdateWithoutNotificationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRequestsNestedInput
  responses?: Prisma.RequestResponseUpdateManyWithoutRequestNestedInput
}

export type ServiceRequestUncheckedUpdateWithoutNotificationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.RequestResponseUncheckedUpdateManyWithoutRequestNestedInput
}

export type ServiceRequestCreateManyUserInput = {
  id?: string
  title: string
  description: string
  category: $Enums.RequestCategory
  status?: $Enums.RequestStatus
  priority?: $Enums.Priority
  location?: string | null
  assignedTo?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceRequestUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.RequestResponseUpdateManyWithoutRequestNestedInput
  notifications?: Prisma.NotificationUpdateManyWithoutRequestNestedInput
}

export type ServiceRequestUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.RequestResponseUncheckedUpdateManyWithoutRequestNestedInput
  notifications?: Prisma.NotificationUncheckedUpdateManyWithoutRequestNestedInput
}

export type ServiceRequestUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumRequestCategoryFieldUpdateOperationsInput | $Enums.RequestCategory
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  assignedTo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ServiceRequestCountOutputType
 */

export type ServiceRequestCountOutputType = {
  responses: number
  notifications: number
}

export type ServiceRequestCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  responses?: boolean | ServiceRequestCountOutputTypeCountResponsesArgs
  notifications?: boolean | ServiceRequestCountOutputTypeCountNotificationsArgs
}

/**
 * ServiceRequestCountOutputType without action
 */
export type ServiceRequestCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequestCountOutputType
   */
  select?: Prisma.ServiceRequestCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ServiceRequestCountOutputType without action
 */
export type ServiceRequestCountOutputTypeCountResponsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestResponseWhereInput
}

/**
 * ServiceRequestCountOutputType without action
 */
export type ServiceRequestCountOutputTypeCountNotificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificationWhereInput
}


export type ServiceRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  status?: boolean
  priority?: boolean
  location?: boolean
  userId?: boolean
  assignedTo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  responses?: boolean | Prisma.ServiceRequest$responsesArgs<ExtArgs>
  notifications?: boolean | Prisma.ServiceRequest$notificationsArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceRequestCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceRequest"]>

export type ServiceRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  status?: boolean
  priority?: boolean
  location?: boolean
  userId?: boolean
  assignedTo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceRequest"]>

export type ServiceRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  status?: boolean
  priority?: boolean
  location?: boolean
  userId?: boolean
  assignedTo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceRequest"]>

export type ServiceRequestSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  status?: boolean
  priority?: boolean
  location?: boolean
  userId?: boolean
  assignedTo?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ServiceRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "category" | "status" | "priority" | "location" | "userId" | "assignedTo" | "createdAt" | "updatedAt", ExtArgs["result"]["serviceRequest"]>
export type ServiceRequestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  responses?: boolean | Prisma.ServiceRequest$responsesArgs<ExtArgs>
  notifications?: boolean | Prisma.ServiceRequest$notificationsArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceRequestCountOutputTypeDefaultArgs<ExtArgs>
}
export type ServiceRequestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ServiceRequestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ServiceRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceRequest"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    responses: Prisma.$RequestResponsePayload<ExtArgs>[]
    notifications: Prisma.$NotificationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string
    category: $Enums.RequestCategory
    status: $Enums.RequestStatus
    priority: $Enums.Priority
    location: string | null
    userId: string
    assignedTo: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["serviceRequest"]>
  composites: {}
}

export type ServiceRequestGetPayload<S extends boolean | null | undefined | ServiceRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload, S>

export type ServiceRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceRequestCountAggregateInputType | true
  }

export interface ServiceRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceRequest'], meta: { name: 'ServiceRequest' } }
  /**
   * Find zero or one ServiceRequest that matches the filter.
   * @param {ServiceRequestFindUniqueArgs} args - Arguments to find a ServiceRequest
   * @example
   * // Get one ServiceRequest
   * const serviceRequest = await prisma.serviceRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceRequestFindUniqueOrThrowArgs} args - Arguments to find a ServiceRequest
   * @example
   * // Get one ServiceRequest
   * const serviceRequest = await prisma.serviceRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceRequestFindFirstArgs} args - Arguments to find a ServiceRequest
   * @example
   * // Get one ServiceRequest
   * const serviceRequest = await prisma.serviceRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceRequestFindFirstOrThrowArgs} args - Arguments to find a ServiceRequest
   * @example
   * // Get one ServiceRequest
   * const serviceRequest = await prisma.serviceRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceRequests
   * const serviceRequests = await prisma.serviceRequest.findMany()
   * 
   * // Get first 10 ServiceRequests
   * const serviceRequests = await prisma.serviceRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serviceRequestWithIdOnly = await prisma.serviceRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServiceRequestFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceRequest.
   * @param {ServiceRequestCreateArgs} args - Arguments to create a ServiceRequest.
   * @example
   * // Create one ServiceRequest
   * const ServiceRequest = await prisma.serviceRequest.create({
   *   data: {
   *     // ... data to create a ServiceRequest
   *   }
   * })
   * 
   */
  create<T extends ServiceRequestCreateArgs>(args: Prisma.SelectSubset<T, ServiceRequestCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceRequests.
   * @param {ServiceRequestCreateManyArgs} args - Arguments to create many ServiceRequests.
   * @example
   * // Create many ServiceRequests
   * const serviceRequest = await prisma.serviceRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServiceRequests and returns the data saved in the database.
   * @param {ServiceRequestCreateManyAndReturnArgs} args - Arguments to create many ServiceRequests.
   * @example
   * // Create many ServiceRequests
   * const serviceRequest = await prisma.serviceRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServiceRequests and only return the `id`
   * const serviceRequestWithIdOnly = await prisma.serviceRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ServiceRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ServiceRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServiceRequest.
   * @param {ServiceRequestDeleteArgs} args - Arguments to delete one ServiceRequest.
   * @example
   * // Delete one ServiceRequest
   * const ServiceRequest = await prisma.serviceRequest.delete({
   *   where: {
   *     // ... filter to delete one ServiceRequest
   *   }
   * })
   * 
   */
  delete<T extends ServiceRequestDeleteArgs>(args: Prisma.SelectSubset<T, ServiceRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceRequest.
   * @param {ServiceRequestUpdateArgs} args - Arguments to update one ServiceRequest.
   * @example
   * // Update one ServiceRequest
   * const serviceRequest = await prisma.serviceRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceRequestUpdateArgs>(args: Prisma.SelectSubset<T, ServiceRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceRequests.
   * @param {ServiceRequestDeleteManyArgs} args - Arguments to filter ServiceRequests to delete.
   * @example
   * // Delete a few ServiceRequests
   * const { count } = await prisma.serviceRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceRequests
   * const serviceRequest = await prisma.serviceRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceRequests and returns the data updated in the database.
   * @param {ServiceRequestUpdateManyAndReturnArgs} args - Arguments to update many ServiceRequests.
   * @example
   * // Update many ServiceRequests
   * const serviceRequest = await prisma.serviceRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServiceRequests and only return the `id`
   * const serviceRequestWithIdOnly = await prisma.serviceRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ServiceRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ServiceRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServiceRequest.
   * @param {ServiceRequestUpsertArgs} args - Arguments to update or create a ServiceRequest.
   * @example
   * // Update or create a ServiceRequest
   * const serviceRequest = await prisma.serviceRequest.upsert({
   *   create: {
   *     // ... data to create a ServiceRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceRequest we want to update
   *   }
   * })
   */
  upsert<T extends ServiceRequestUpsertArgs>(args: Prisma.SelectSubset<T, ServiceRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceRequestClient<runtime.Types.Result.GetResult<Prisma.$ServiceRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceRequestCountArgs} args - Arguments to filter ServiceRequests to count.
   * @example
   * // Count the number of ServiceRequests
   * const count = await prisma.serviceRequest.count({
   *   where: {
   *     // ... the filter for the ServiceRequests we want to count
   *   }
   * })
  **/
  count<T extends ServiceRequestCountArgs>(
    args?: Prisma.Subset<T, ServiceRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceRequestAggregateArgs>(args: Prisma.Subset<T, ServiceRequestAggregateArgs>): Prisma.PrismaPromise<GetServiceRequestAggregateType<T>>

  /**
   * Group by ServiceRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceRequestGroupByArgs['orderBy'] }
      : { orderBy?: ServiceRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceRequest model
 */
readonly fields: ServiceRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  responses<T extends Prisma.ServiceRequest$responsesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceRequest$responsesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  notifications<T extends Prisma.ServiceRequest$notificationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceRequest$notificationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceRequest model
 */
export interface ServiceRequestFieldRefs {
  readonly id: Prisma.FieldRef<"ServiceRequest", 'String'>
  readonly title: Prisma.FieldRef<"ServiceRequest", 'String'>
  readonly description: Prisma.FieldRef<"ServiceRequest", 'String'>
  readonly category: Prisma.FieldRef<"ServiceRequest", 'RequestCategory'>
  readonly status: Prisma.FieldRef<"ServiceRequest", 'RequestStatus'>
  readonly priority: Prisma.FieldRef<"ServiceRequest", 'Priority'>
  readonly location: Prisma.FieldRef<"ServiceRequest", 'String'>
  readonly userId: Prisma.FieldRef<"ServiceRequest", 'String'>
  readonly assignedTo: Prisma.FieldRef<"ServiceRequest", 'String'>
  readonly createdAt: Prisma.FieldRef<"ServiceRequest", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ServiceRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ServiceRequest findUnique
 */
export type ServiceRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
  /**
   * Filter, which ServiceRequest to fetch.
   */
  where: Prisma.ServiceRequestWhereUniqueInput
}

/**
 * ServiceRequest findUniqueOrThrow
 */
export type ServiceRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
  /**
   * Filter, which ServiceRequest to fetch.
   */
  where: Prisma.ServiceRequestWhereUniqueInput
}

/**
 * ServiceRequest findFirst
 */
export type ServiceRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
  /**
   * Filter, which ServiceRequest to fetch.
   */
  where?: Prisma.ServiceRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceRequests to fetch.
   */
  orderBy?: Prisma.ServiceRequestOrderByWithRelationInput | Prisma.ServiceRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceRequests.
   */
  cursor?: Prisma.ServiceRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceRequests.
   */
  distinct?: Prisma.ServiceRequestScalarFieldEnum | Prisma.ServiceRequestScalarFieldEnum[]
}

/**
 * ServiceRequest findFirstOrThrow
 */
export type ServiceRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
  /**
   * Filter, which ServiceRequest to fetch.
   */
  where?: Prisma.ServiceRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceRequests to fetch.
   */
  orderBy?: Prisma.ServiceRequestOrderByWithRelationInput | Prisma.ServiceRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceRequests.
   */
  cursor?: Prisma.ServiceRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceRequests.
   */
  distinct?: Prisma.ServiceRequestScalarFieldEnum | Prisma.ServiceRequestScalarFieldEnum[]
}

/**
 * ServiceRequest findMany
 */
export type ServiceRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
  /**
   * Filter, which ServiceRequests to fetch.
   */
  where?: Prisma.ServiceRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceRequests to fetch.
   */
  orderBy?: Prisma.ServiceRequestOrderByWithRelationInput | Prisma.ServiceRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceRequests.
   */
  cursor?: Prisma.ServiceRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceRequests.
   */
  skip?: number
  distinct?: Prisma.ServiceRequestScalarFieldEnum | Prisma.ServiceRequestScalarFieldEnum[]
}

/**
 * ServiceRequest create
 */
export type ServiceRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceRequest.
   */
  data: Prisma.XOR<Prisma.ServiceRequestCreateInput, Prisma.ServiceRequestUncheckedCreateInput>
}

/**
 * ServiceRequest createMany
 */
export type ServiceRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceRequests.
   */
  data: Prisma.ServiceRequestCreateManyInput | Prisma.ServiceRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServiceRequest createManyAndReturn
 */
export type ServiceRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * The data used to create many ServiceRequests.
   */
  data: Prisma.ServiceRequestCreateManyInput | Prisma.ServiceRequestCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceRequest update
 */
export type ServiceRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceRequest.
   */
  data: Prisma.XOR<Prisma.ServiceRequestUpdateInput, Prisma.ServiceRequestUncheckedUpdateInput>
  /**
   * Choose, which ServiceRequest to update.
   */
  where: Prisma.ServiceRequestWhereUniqueInput
}

/**
 * ServiceRequest updateMany
 */
export type ServiceRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceRequests.
   */
  data: Prisma.XOR<Prisma.ServiceRequestUpdateManyMutationInput, Prisma.ServiceRequestUncheckedUpdateManyInput>
  /**
   * Filter which ServiceRequests to update
   */
  where?: Prisma.ServiceRequestWhereInput
  /**
   * Limit how many ServiceRequests to update.
   */
  limit?: number
}

/**
 * ServiceRequest updateManyAndReturn
 */
export type ServiceRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * The data used to update ServiceRequests.
   */
  data: Prisma.XOR<Prisma.ServiceRequestUpdateManyMutationInput, Prisma.ServiceRequestUncheckedUpdateManyInput>
  /**
   * Filter which ServiceRequests to update
   */
  where?: Prisma.ServiceRequestWhereInput
  /**
   * Limit how many ServiceRequests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceRequest upsert
 */
export type ServiceRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceRequest to update in case it exists.
   */
  where: Prisma.ServiceRequestWhereUniqueInput
  /**
   * In case the ServiceRequest found by the `where` argument doesn't exist, create a new ServiceRequest with this data.
   */
  create: Prisma.XOR<Prisma.ServiceRequestCreateInput, Prisma.ServiceRequestUncheckedCreateInput>
  /**
   * In case the ServiceRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceRequestUpdateInput, Prisma.ServiceRequestUncheckedUpdateInput>
}

/**
 * ServiceRequest delete
 */
export type ServiceRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
  /**
   * Filter which ServiceRequest to delete.
   */
  where: Prisma.ServiceRequestWhereUniqueInput
}

/**
 * ServiceRequest deleteMany
 */
export type ServiceRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceRequests to delete
   */
  where?: Prisma.ServiceRequestWhereInput
  /**
   * Limit how many ServiceRequests to delete.
   */
  limit?: number
}

/**
 * ServiceRequest.responses
 */
export type ServiceRequest$responsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestResponse
   */
  select?: Prisma.RequestResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestResponse
   */
  omit?: Prisma.RequestResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestResponseInclude<ExtArgs> | null
  where?: Prisma.RequestResponseWhereInput
  orderBy?: Prisma.RequestResponseOrderByWithRelationInput | Prisma.RequestResponseOrderByWithRelationInput[]
  cursor?: Prisma.RequestResponseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RequestResponseScalarFieldEnum | Prisma.RequestResponseScalarFieldEnum[]
}

/**
 * ServiceRequest.notifications
 */
export type ServiceRequest$notificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  where?: Prisma.NotificationWhereInput
  orderBy?: Prisma.NotificationOrderByWithRelationInput | Prisma.NotificationOrderByWithRelationInput[]
  cursor?: Prisma.NotificationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NotificationScalarFieldEnum | Prisma.NotificationScalarFieldEnum[]
}

/**
 * ServiceRequest without action
 */
export type ServiceRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceRequest
   */
  select?: Prisma.ServiceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceRequest
   */
  omit?: Prisma.ServiceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceRequestInclude<ExtArgs> | null
}
